// check the api using api client
### test GET /getSchema
GET http://localhost:3000/dev/schema?id=w1qbLlcdHNwi5zLyBBFUK

### test GET /getSchema
GET http://localhost:3000/dev/todos
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdaOXFhYUJEYXM0SjZzSEhQWlVMWSJ9.eyJpc3MiOiJodHRwczovL2Rldi1nbGEyNHhraGl4OGk0aG91LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwODI1NjI1MTk5NDgxODk0ODEyMyIsImF1ZCI6WyJodHRwczovL2Rldi1nbGEyNHhraGl4OGk0aG91LnVzLmF1dGgwLmNvbS9hcGkvdjIvIiwiaHR0cHM6Ly9kZXYtZ2xhMjR4a2hpeDhpNGhvdS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjk2NTkzMjU1LCJleHAiOjE2OTY2Nzk2NTUsImF6cCI6Im9RY3gwRlhhcUZycXF0OUdjdzMzZUNtWmxESWJNc0RjIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.XNDkWfTc1PT53u8NIbkcEKtr3hnJ8u79iPZD7Qz1rX0eyxjs4w1fHv9lKnH7Bw_10hypywnznJqI6tuuMOmqydZWLTqlccV045s-NJr2Ab5Zf3-Jo_vKX_3k4JjXFLZhT63DGwQNPg5V2q6MMipmLXgzX6xU-7QWIcLqPjyLwEFlfytZ4NIc37BKhjEOMvmVgagrmdkMznqHk7HTj0gVwnE4-rt3MoBonP-Ebsr9ObzAqCjM-aLwX80562Bv0d3_rRx75dhke884vqU8cQ7nSL2FgMNuYshXrmoDMMvWdLJVLdf_Wd3aA5Ue1XlE-YsgfP42Ork5D6chcxVjg40TNA
### test GET /getSchema
GET https://qdkwnpwrkf.execute-api.us-east-2.amazonaws.com/dev/todos
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdaOXFhYUJEYXM0SjZzSEhQWlVMWSJ9.eyJpc3MiOiJodHRwczovL2Rldi1nbGEyNHhraGl4OGk0aG91LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwODI1NjI1MTk5NDgxODk0ODEyMyIsImF1ZCI6WyJodHRwczovL2Rldi1nbGEyNHhraGl4OGk0aG91LnVzLmF1dGgwLmNvbS9hcGkvdjIvIiwiaHR0cHM6Ly9kZXYtZ2xhMjR4a2hpeDhpNGhvdS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjk2NTkzMjU1LCJleHAiOjE2OTY2Nzk2NTUsImF6cCI6Im9RY3gwRlhhcUZycXF0OUdjdzMzZUNtWmxESWJNc0RjIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.XNDkWfTc1PT53u8NIbkcEKtr3hnJ8u79iPZD7Qz1rX0eyxjs4w1fHv9lKnH7Bw_10hypywnznJqI6tuuMOmqydZWLTqlccV045s-NJr2Ab5Zf3-Jo_vKX_3k4JjXFLZhT63DGwQNPg5V2q6MMipmLXgzX6xU-7QWIcLqPjyLwEFlfytZ4NIc37BKhjEOMvmVgagrmdkMznqHk7HTj0gVwnE4-rt3MoBonP-Ebsr9ObzAqCjM-aLwX80562Bv0d3_rRx75dhke884vqU8cQ7nSL2FgMNuYshXrmoDMMvWdLJVLdf_Wd3aA5Ue1XlE-YsgfP42Ork5D6chcxVjg40TNA

### test GET /getSchema
DELETE http://localhost:3000/dev/todos/53uFmgVKXQFuooKKMRTOJ

### generate prisigned URL
POST http://localhost:3000/dev/todos/53uFmgVKXQFuooKKMRTOJ/attachment

### test POST /createSchema
POST http://localhost:3000/dev/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdaOXFhYUJEYXM0SjZzSEhQWlVMWSJ9.eyJpc3MiOiJodHRwczovL2Rldi1nbGEyNHhraGl4OGk0aG91LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwODI1NjI1MTk5NDgxODk0ODEyMyIsImF1ZCI6WyJodHRwczovL2Rldi1nbGEyNHhraGl4OGk0aG91LnVzLmF1dGgwLmNvbS9hcGkvdjIvIiwiaHR0cHM6Ly9kZXYtZ2xhMjR4a2hpeDhpNGhvdS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjk2NTkzMjU1LCJleHAiOjE2OTY2Nzk2NTUsImF6cCI6Im9RY3gwRlhhcUZycXF0OUdjdzMzZUNtWmxESWJNc0RjIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.XNDkWfTc1PT53u8NIbkcEKtr3hnJ8u79iPZD7Qz1rX0eyxjs4w1fHv9lKnH7Bw_10hypywnznJqI6tuuMOmqydZWLTqlccV045s-NJr2Ab5Zf3-Jo_vKX_3k4JjXFLZhT63DGwQNPg5V2q6MMipmLXgzX6xU-7QWIcLqPjyLwEFlfytZ4NIc37BKhjEOMvmVgagrmdkMznqHk7HTj0gVwnE4-rt3MoBonP-Ebsr9ObzAqCjM-aLwX80562Bv0d3_rRx75dhke884vqU8cQ7nSL2FgMNuYshXrmoDMMvWdLJVLdf_Wd3aA5Ue1XlE-YsgfP42Ork5D6chcxVjg40TNA

{
    "name": "Buy bread",
    "dueDate": "2022-12-12"
}

### test POST /createSchema
PATCH http://localhost:3000/dev/todos/f6N3F_bUO0_U1vzOjbRq5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdaOXFhYUJEYXM0SjZzSEhQWlVMWSJ9.eyJpc3MiOiJodHRwczovL2Rldi1nbGEyNHhraGl4OGk0aG91LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwODI1NjI1MTk5NDgxODk0ODEyMyIsImF1ZCI6WyJodHRwczovL2Rldi1nbGEyNHhraGl4OGk0aG91LnVzLmF1dGgwLmNvbS9hcGkvdjIvIiwiaHR0cHM6Ly9kZXYtZ2xhMjR4a2hpeDhpNGhvdS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjk2NTkzMjU1LCJleHAiOjE2OTY2Nzk2NTUsImF6cCI6Im9RY3gwRlhhcUZycXF0OUdjdzMzZUNtWmxESWJNc0RjIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.XNDkWfTc1PT53u8NIbkcEKtr3hnJ8u79iPZD7Qz1rX0eyxjs4w1fHv9lKnH7Bw_10hypywnznJqI6tuuMOmqydZWLTqlccV045s-NJr2Ab5Zf3-Jo_vKX_3k4JjXFLZhT63DGwQNPg5V2q6MMipmLXgzX6xU-7QWIcLqPjyLwEFlfytZ4NIc37BKhjEOMvmVgagrmdkMznqHk7HTj0gVwnE4-rt3MoBonP-Ebsr9ObzAqCjM-aLwX80562Bv0d3_rRx75dhke884vqU8cQ7nSL2FgMNuYshXrmoDMMvWdLJVLdf_Wd3aA5Ue1XlE-YsgfP42Ork5D6chcxVjg40TNA

{
    "name": "Buy milk",
    "dueDate": "2022-12-12",
    "done": true
}